version: "3.8"
services:
  portfolio:
    image: node:alpine
    deploy:
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
        - "io.portainer.update.strategy=on-push"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "io.portainer.update.strategy=on-push"
      - "io.portainer.gitops.enabled=true"
