version: "3"

services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  ghost:
    image: ghost:5-alpine
    ports:
      - "2368:2368"
    environment:
      - url=http://localhost:2368
    volumes:
      - ghost_data:/var/lib/ghost/content
    restart: always

volumes:
  ghost_data:
