services:
  nextjs:
    image: node:18-alpine
    command: sh -c "echo 'Hello from Next.js container' && tail -f /dev/null"
    ports:
      - "3000:3000"

  ghost:
    image: ghost:5-alpine
    ports:
      - "2368:2368"
    environment:
      - url=http://localhost:2368
      - database__client=sqlite3
      - database__connection__filename=/var/lib/ghost/content/data/ghost.db
    volumes:
      - ghost_data:/var/lib/ghost/content
    restart: always

volumes:
  ghost_data:
