services:
  nextjs:
    image: node:18-alpine
    command: sh -c "echo 'Hello from Next.js container' && tail -f /dev/null"
    ports:
      - "3000:3000"

  ghost:
    image: ghost:5-alpine
    ports:
      - "2368:2368"
    environment:
      - url=http://localhost:2368
    volumes:
      - ghost_data:/var/lib/ghost/content

volumes:
  ghost_data:
