services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    deploy:
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
        - "traefik.enable=true"
        - "traefik.http.routers.portfolio.rule=Host(`your-domain.com`)"
        - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
    restart: always
